### ISSUE TITLE
Add the possibility to add a custom label to ALL metrics generated

### ISSUE THREAD

**Issue by giorgiodig** [vitalics/playwright-prometheus-remote-write-reporter#11]
We are running playwright tests for multiple environments (dev, stage, prod), and it would be very nice to add a custom label support in playwright.config.js,  for ALL metrics generated by playwright, so we can differentiate between environments when building dashboards, alerts, etc.

Right now we are doing a non-ideal thing of creating different prefixes based on the environment, but it is not ideal for us as it:
- generates duplicated metrics
- makes dashboarding harder, as we can't filter by label name, but we have to hardcode metrics name (and prefixes)

Thanks!

**Comment by xTrekStorex** [comment]
see #9  & #10

**Comment by vitalics** [comment]
close as duplicate of #9
