### ISSUE TITLE
Basic/Minimal Grafana Dashboard with Basic functionality

### ISSUE THREAD

**Issue by giorgiodig** [vitalics/playwright-prometheus-remote-write-reporter#19]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be nice to have in the doc, a basic Grafana Dashboard to visualize tests coming out of this

**Comment by vitalics** [comment]
Hi @giorgiodig. Reporter used for Prometheus only. I know that grafana can visualize info from Prometheus, but now it's an out of scope. You can find connectivity [doc here](https://prometheus.io/docs/visualization/grafana/)

Feel free to create MR for example folder and reopen issue if you have any questions.
