### ISSUE TITLE
Update prometheus-remote-write version

### ISSUE THREAD

**Issue by deefdragon** [vitalics/playwright-prometheus-remote-write-reporter#20]
**Describe the bug**
Due to a header requirement change, the newer versions of Prometheus are not compatible with this package without setting an override. 

This should be fixable by updating the dependency to require at least 0.5.0 of prometheus-remote-write

https://github.com/huksley/prometheus-remote-write/releases/tag/v0.5.0

**Comment by vitalics** [comment]
released at 0.1.1 version
