### ISSUE TITLE
Add external_labels option or static label 'instance' - prevent out of order samples or duplicate samples for timestamp with multiple instances of pw/reporter

### ISSUE THREAD

**Issue by xTrekStorex** [vitalics/playwright-prometheus-remote-write-reporter#9]
**Is your feature request related to a problem? Please describe.**
When more than one instance of playwright with this reporter are run in parallel, e.g. when tests are spread across multiple instances via sharding, the remote written timeseries clash in prometheus with either out of order samples or duplicate samples for timestamp.
This is mainly caused by metrics like pw_tests_pass_count not setting unique labels.
For scrape targets this is usually worked around using the instance and job labels.
For remote write there usually are external_labels which can be added to each series - e.g. source_prometheus.

**Describe the solution you'd like**
I'd like an extra_labels option for the reporter.
These could be done like headers and passed as 'labels' in options/config for [prometheus-remote-write](https://www.npmjs.com/package/prometheus-remote-write#:~:text=e.%20%5B%7B%20service%3A%20%22SQS%22%20%7D%5D-,labels,-%3A%20undefined%2C) just by adding 'labels' to [PrometheusOptions](https://github.com/vitalics/playwright-prometheus-remote-write-reporter/blob/main/src/index.ts#L30) & the [constructor](https://github.com/vitalics/playwright-prometheus-remote-write-reporter/blob/main/src/index.ts#L223).

**Describe alternatives you've considered**
A hardcoded label instance=$hostname or similar to identify the instance writing to prometheus.
Added here to be inherited by all metrics: https://github.com/vitalics/playwright-prometheus-remote-write-reporter/blob/main/src/helpers.ts#L15

**Comment by vitalics** [comment]
Hi, thanks for your issue. Could you please add repo with steps, it helps me improve this library

**Comment by xTrekStorex** [comment]
> Hi, thanks for your issue. Could you please add repo with steps, it helps me improve this library

Hi, do you mean #10 ?
